name: getting aws secrets manager secrets into github actions

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    - name: test
      run: aws sts get-caller-identity
    - name: get aws secrets
      id: get_secret
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          AWESOME_SECRET
    - name: echo secret
      run: |
        echo ${{env.AWESOME_SECRET}}

    - name: Set GitHub Token as an environment variable
      run: echo "GITHUB_TOKEN=${{ steps.get_secret.outputs.secretString }}" >> $GITHUB_ENV
    - name: checkout
      uses: actions/checkout@v3
    - name: Print GitHub Token
      run: |
        echo "GitHub Token: $GITHUB_TOKEN"

