name: getting aws secrets manager secrets into github actions

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-2
    - name: test
      run: aws sts get-caller-identity
