name: getting aws secrets manager secrets into github actions

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    - name: test
      run: aws sts get-caller-identity
    - name: get aws secrets
      uses: aws-actions/aws-secretsmanaget-get-secrets@v1
      with:
        secret-ids: |
          key/sample
    - name: echo secret
      run: |
        echo ${{env.key/sample}}
