name: getting aws secrets manager secrets into github actions

on:
  push:
    - develop
    - main
    - master
  workflow_dispatch:

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::559954683639:role/custom_oidc
        aws-region: us-east-2
    - name: test
      run: aws sts get-caller-identity
